# Configuration file

# Version of the config
version: 1.0
# Plugin language
language: en
# The materials that allowed to be installed.
materials:
  - 'WOODEN_SWORD'
  - 'STONE_SWORD'
  - 'IRON_SWORD'
  - 'DIAMOND_SWORD'
  - 'NETHERITE_SWORD'
  - 'WOODEN_AXE'
  - 'STONE_AXE'
  - 'IRON_AXE'
  - 'DIAMOND_AXE'
  - 'NETHERITE_AXE'
  - 'LEATHER_HELMET'
  - 'LEATHER_CHESTPLATE'
  - 'LEATHER_LEGGINGS'
  - 'LEATHER_BOOTS'
  - 'GOLDEN_HELMET'
  - 'GOLDEN_CHESTPLATE'
  - 'GOLDEN_LEGGINGS'
  - 'GOLDEN_BOOTS'
  - 'IRON_HELMET'
  - 'IRON_CHESTPLATE'
  - 'IRON_LEGGINGS'
  - 'IRON_BOOTS'
  - 'DIAMOND_HELMET'
  - 'DIAMOND_CHESTPLATE'
  - 'DIAMOND_LEGGINGS'
  - 'DIAMOND_BOOTS'
  - 'NETHERITE_HELMET'
  - 'NETHERITE_CHESTPLATE'
  - 'NETHERITE_LEGGINGS'
  - 'NETHERITE_BOOTS'
  - 'CHAINMAIL_HELMET'
  - 'CHAINMAIL_CHESTPLATE'
  - 'CHAINMAIL_LEGGINGS'
  - 'CHAINMAIL_BOOTS'