main: p1xel.minecraft.bukkit.GemInstall
name: GemInstall
version: 1.0.0
api-version: 1.13
softdepend: [Vault]
commands:
  geminstall:
    aliases: [gi]

permissions:
  geminstall.use:
    default: true
  geminstall:admin:
    default: op